
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: psqlapp_development

test:
  <<: *default
  database: psqlapp_test

production:
  <<: *default
  database: psqlapp_production
  username: psqlapp
  password: <%= ENV['PSQLAPP_DATABASE_PASSWORD'] %>